//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::modem_events::{
    Column as ModemEventsColumn, Entity as ModemEvents, Model as ModemEvent,
};
pub use super::outtages::{Column as OuttagesColumn, Entity as Outtages, Model as Outtage};
