//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::modem_events::Entity as ModemEvents;
pub use super::outtages::Entity as Outtages;
pub use super::outtages::Column as OuttagesColumn;
